## NumPy is faster than List

Numpy uses contiguous blocks of memory for storing its data. This means that NumPy can access elements in its array more efficiently than a list because the data is stored in a single block of memory, which allows for faster memory access and improved performance.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimension in Arrays

## 0-D Arrays

In [3]:
arr0 = np.array([123])
print(arr0)
arr0.ndim # check number of dimension

[123]


1

## 1-D Arrays

In [4]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
arr1.ndim

[1 2 3 4 5]


1

## 2-D Arrays

In [5]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
arr2.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

## 3-D Arrays

In [6]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,3,4],[3,4,5]]])
print(arr3)
arr3.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 3 4]
  [3 4 5]]]


3

## Higher Dimension

In [7]:
arr4 = np.array([1,2,3,4,5], ndmin=6)
print(arr4)
print(arr4.ndim)

[[[[[[1 2 3 4 5]]]]]]
6
